version: '2'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - 15673:15672
  registry:
    image: kaisagroup_micro/registry
    ports:
      - "8761:8761"
  config:
    image: kaisagroup_micro/config
    ports:
      - "8888:8888"
  monitor:
    image: kaisagroup_micro/monitor
    ports:
      - "8040:8040"
  zipkin:
    image: kaisagroup_micro/zipkin
    ports:
      - "9411:9411"
  gateway:
    image: kaisagroup_micro/gateway
    ports:
      - "8060:8060"
  auth-service:
    image: kaisagroup_micro/auth-service
    ports:
      - "5000:5000"
  testa-service:
    image: kaisagroup_micro/testa-service
  testb-service:
    image: kaisagroup_micro/testb-service