server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

#spring:
#  datasource:
#    url: jdbc:h2:mem:user
#    driver-class-name: org.h2.Driver
#  jpa:
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2test?characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 5
    max-wait: 10000
    min-idle: 2
    initial-size: 3
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 18800
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)

security:
    oauth2:
        resource:
           id: oauth2-resource
           token-info-uri: http://localhost:8080/oauth/check_token
           prefer-token-info: true
